### ISSUE TITLE
ESP8266 vs ESP12S

### ISSUE THREAD

**Issue by dicastro** [ArnieX/swifitch#10]
I have just realized that the link for the ESP8266 points to an ESP12S. This one (ESP12S has only connectors in both laterals only). Is this one compatible?

I have bought all the components following your links. Maybe aliexpress has changed the component?

(All the photos in your repo have swifitches using ESP8266)

**Comment by ArnieX** [comment]
Yes ESP8266-12S is compatible. It is newer version and those pins on the back aren’t used for anything. I do not even solder these when using 12E or 12F versions. Basically most ESP versions from 7 up are supported. But I suggest you stick with 12E/F/S.

**Comment by dicastro** [comment]
Thank you!
