### ISSUE TITLE
How to control multiple relays?

### ISSUE THREAD

**Issue by KrishnaPG** [ArnieX/swifitch#3]
Thanks for sharing this good work. It is helpful.

Wondering if you have this design extended for controlling more than one relay. And also, how to make it work with dimmers etc (in the same board alongside with normal relays)?

**Comment by ArnieX** [comment]
Hi, this is what header is for. You can connect extra accessories to the board. If you would like it to control big relay board that should be possible if this board would be equipped with I2C. Dimmers would work too but for that I recommend dimmer that is referenced in “What’s next” in readme.

**Comment by KrishnaPG** [comment]
Thanks for quick reply @ArnieX Will look into the header functionality. Thanks again for sharing this good work.

**Comment by ArnieX** [comment]
You are welcome, hope you will like it if you happen to build few.

**Comment by KrishnaPG** [comment]
In the folder which file is the board file? I am trying to experiment with the board to make small changes, such as using nodemcu (in place of esp), and other options such as using mounting headers instead of having to solder etc. Could not find the source files in the repo

**Comment by ArnieX** [comment]
Sorry, no source file available. Using NodeMCU is overkill. Anyway NodeMCU is good for prototyping, this is actually finished thing. If you want to use NodeMCU the best would be to use other ready made modules, like relay module, etc.

**Comment by KrishnaPG** [comment]
Thanks. When sending this design for PCB manufacturer (local) for a quote, they are asking for BOM. Wondering if there is BOM csv file that you can share?

**Comment by ArnieX** [comment]
Well, I'm not sure. PCB manufacturers usually need gerber files. I don't know what is BOM, but I can ask my colleague who did the actual PCB design, if he knows what this is.

**Comment by KrishnaPG** [comment]
BOM is short for "Bill of Materials". They would need it to assemble components on the PCB (after the creation), and also to give the estimate/quote. Essentially it tells which component goes to which location (on the PCB) and how many needed and what is the exact component brand/value etc.

**Comment by ArnieX** [comment]
Hi, this information is in readme. You can therefor assemble BOM file yourself ;)

**Comment by KrishnaPG** [comment]
Thanks. Wish I were that expert :)
The system (that generated the gerber etc.), must have auto-generated all these BOM automatically.  It follows certain format. Besides, I want to make sure that their placement mappings (which is not provided in the readme) is correctly captured. Request you to kindly check with your mentioned Friend - he must already be having this BOM file. It would be great help.

**Comment by KrishnaPG** [comment]
Also, the placement mapping of these components is important. For example, there are multiple resistors listed in the parts. The generated BOM file keeps the mapping correct.

**Comment by ArnieX** [comment]
Just one question. Are you going to make it in big amounts? If not we recommend you to solder manually.

**Comment by KrishnaPG** [comment]
Not big amounts. I am more of software guy, so I am asking my friends to help me build samples. In that process, they asked me to get the BOM. It helps them to recreate the board correctly. Hence the request.

**Comment by ArnieX** [comment]
Then again, exact mapping table is included in readme. This should be more than sufficient to do exactly what you need. I use it too when soldering.
